apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
  labels:
    app: addressbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook

    spec:
      containers:
      - name: addressbook
        image: gururajdockerusername/star:latest
        ports:
        - containerPort: 8080
